language: node_js
node_js: 
  - "10"
script:
  - npm install -g istanbul
  - npm install -g codecov
  - npm run cover
  - codecov
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
